<a href="https://colab.research.google.com/github/ShubhamTiwary914/MachineLearning_Notebooks/blob/main/4_WordSentiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow import keras

### Dummy Datasets

In [ ]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiments = np.array([1,1,1,1,1,0,0,0,0,0])

### Encoding + Padding the Words

In [ ]:
def analyseSentences():
  res = [0, 0]
  for review in reviews:
    words = review.split(' ')
    res[0] = max(res[0], len(review))
    res[1] = max(res[1], len(words))
  return res
res = analyseSentences()
charsMax = res[0]*2
wordsMax = res[1]+1

#One Hot Encoding
reviewsEncoded = [one_hot(review, charsMax) for review in reviews]
#Padding
reviewsPadded = pad_sequences(reviewsEncoded, maxlen=wordsMax, padding='post')

print(reviewsPadded)

[[10 10  0  0]
 [10 30  0  0]
 [28 26  0  0]
 [ 9 28  9  0]
 [15  4 28  0]
 [18 10  0  0]
 [15  4 16  0]
 [27 23  0  0]
 [27 19  0  0]
 [21 35  0  0]]


### DL Model Generates Word Embedding

In [ ]:
model = keras.Sequential([
    keras.layers.Embedding(charsMax, 5, input_length=wordsMax, name="words-embedding"),
    keras.layers.Flatten(),
    keras.layers.Dense(1, activation='sigmoid')
])


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(reviewsPadded, sentiments, epochs=50, verbose=0)

### Model Summary & Evaluation

In [ ]:
print(model.summary())

# evaluate the model
loss, accuracy = model.evaluate(reviewsPadded, sentiments)
accuracy

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 words-embedding (Embedding  (None, 4, 5)              180       
 )                                                               
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 201 (804.00 Byte)
Trainable params: 201 (804.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
1/1 [==============================] - 0s 130ms/step - loss: 0.6229 - accuracy: 1.0000


1.0